---
- name: check installed
  ansible.builtin.command:
    cmd: "pwsh -nop -noni -c 'Get-Module PSScriptAnalyzer -ListAvailable'"
  register: module
  changed_when: false
  failed_when: false

- name: install
  when: module.stdout == ""
  ansible.builtin.command:
    cmd: "pwsh -nop -noni -c 'Install-Module PSScriptAnalyzer -Force'"
