---
namespace: x_delfino
name: cloud
version: 0.0.4
description: collection of cloud tools
tags: []
authors: delfino

readme: README.md
license:
  - GPL-2.0-or-later
license_file: ''

dependencies: {}

repository: https://github.com/x-delfino/ansible-collections/tree/main/cloud
documentation: https://github.com/x-delfino/ansible-collections/tree/main/cloud
homepage: https://github.com/x-delfino/ansible-collections
issues: https://github.com/x-delfino/ansible-collections/issues

build_ignore: []
