---
- name: ensure python3 and pip are installed
  ansible.builtin.apt:
    name:
      - python3
      - python3-pip
    state: present
    update_cache: true
  become: true

- name: install
  ansible.builtin.pip:
    name: pyftpdlib
    state: present
    executable: pip3
