---
- name: quick config
  when: winrm_quickconfig
  ansible.windows.win_command: .\winrm.cmd quickconfig -q
  args:
    chdir: c:\windows\system32
  register: winrm_quickconfig
  changed_when: >
    winrm_quickconfig.stdout_lines[0] !=
    "WinRM service is already running on this machine."

- name: set max memory per shell
  ansible.windows.win_command: |
    winrm.cmd set winrm/config/winrs @{MaxMemoryPerShellMB="512"}
  args:
    chdir: c:\windows\system32
  register: winrm_maxmemory

- name: set max timeout
  ansible.windows.win_command: >
    "{{
      'winrm.cmd set winrm/config @{MaxTimeoutms=\"' +
    winrm_timeout +
    '\"}'
    }}"
  args:
    chdir: c:\windows\system32
  register: winrm_maxtimeout

- name: set allow unencrypted
  when: winrm_unencrypted
  ansible.windows.win_command: |
    winrm.cmd set winrm/config/service @{AllowUnencrypted="true"}
  args:
    chdir: c:\windows\system32
  register: winrm_unencrypted

- name: set basic auth
  when: winrm_basicauth
  ansible.windows.win_command: |
    winrm.cmd set winrm/config/service/auth @{Basic="true"}
  args:
    chdir: c:\windows\system32
  register: winrm_basicauth
