---
- hosts: "{{target|default('all')}}"
  roles:
    - alacritty
    - curl
    - git
    - golang
    - neovim
    - nnn
    - ohmyzsh
    - powershell
    - ps_script_analyzer
    - python3_9_venv
    - rust
    - rust_analyzer
    - tmux
    - tmuxp
    - tpm
    - unzip
    - vim_plug
    - wget
    - zip
    - zsh
