---
- name: group hosts
  hosts: all
  tasks:
    - name: group hosts depending on their OS type
      ansible.builtin.group_by:
        key: os_{{ ansible_system | lower }}

- hosts: "{{ 'os_linux:&' + target|default('all')}}"
  roles:
    - alacritty
    - curl
    - git
    - golang
    - nnn
    - ohmyzsh
    - powershell
    - ps_script_analyzer
    - python3_9_venv
    - rust
    - rust_analyzer
    - tmux
    - tmuxp
    - tpm
    - unzip
    - vim_plug
    - wget
    - zip
    - zsh

- hosts: "{{target|default('all')}}"
  roles:
    - neovim
