---
- name: group hosts
  hosts: all
  tasks:
    - name: group hosts depending on their OS type
      ansible.builtin.group_by:
        key: os_{{ ansible_system | lower }}
      changed_when: false

- hosts: "{{ 'os_linux:&' + target|default('all')}}"
  roles:
    - curl
    - nnn
    - ohmyzsh
    - tmux
    - tmuxp
    - tpm
    - unzip
    - vim_plug
    - wget
    - zip
    - zsh

- hosts: "{{target|default('all')}}"
  roles:
    - alacritty
    - git
    - golang
    - neovim
    - powershell
    - ps_script_analyzer
    - py3_virtualenv
    - python3
    - rust
    - rust_analyzer
