---
namespace: x_delfino
name: security
version: 0.0.3
description: selection of security tools
tags: []
authors: delfino

readme: README.md
license:
  - GPL-2.0-or-later
license_file: ''

dependencies: {}

repository: https://github.com/x-delfino/ansible-collections/tree/main/security
documentation: https://github.com/x-delfino/ansible-collections/tree/main/security
homepage: https://github.com/x-delfino/ansible-collections
issues: https://github.com/x-delfino/ansible-collections/issues

build_ignore: []
