---
- name: ensure vim-plug dir
  ansible.builtin.file:
    path: "{{ vim_plug_dir }}"
    state: directory
    mode: 0750

- name: install vim-plug
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ vim_plug_path }}"
    mode: 0644
