---
- name: check if installed
  ansible.builtin.file:
    state: file
    path: "{{ tools_dir + '/rust-analyzer' }}"
  register: installed
  failed_when: false
  changed_when: false

- name: install
  when: installed.state == 'absent'
  include_tasks: install.yml
