---
- name: check installed
  ansible.windows.win_powershell:
    script: |
      Get-PackageProvider NuGet -ListAvailable -ErrorAction Ignore
  register: provider

- name: install
  when: provider.host_out == ""
  ansible.windows.win_powershell:
    script: |
      Install-PackageProvider NuGet -Force
