---
- name: check installed
  ansible.windows.win_powershell:
    script: |
      Get-PackageProvider NuGet -ListAvailable -ErrorAction Ignore
  changed_when: false
  register: provider

- name: install
  when: provider.output[0].Name != "NuGet"
  ansible.windows.win_powershell:
    script: |
      Install-PackageProvider NuGet -Force
  register: install
  changed_when: install.host_err == ""
