---
namespace: x_delfino
name: jobs
version: 0.0.2
description: collection of jobs
tags: []
authors: delfino

readme: README.md
license:
  - GPL-2.0-or-later
license_file: ''

dependencies: {}

repository: https://github.com/x-delfino/ansible-collections/tree/main/jobs
documentation: https://github.com/x-delfino/ansible-collections/tree/main/jobs
homepage: https://github.com/x-delfino/ansible-collections
issues: https://github.com/x-delfino/ansible-collections/issues

build_ignore: []
