---
namespace: x_delfino
name: utils
version: 0.0.8
description: collection of utils
tags: []
authors: delfino

readme: README.md
license:
  - GPL-2.0-or-later
license_file: ''

dependencies: {}

repository: https://github.com/x-delfino/ansible-collections/tree/main/utils
documentation: https://github.com/x-delfino/ansible-collections/tree/main/utils
homepage: https://github.com/x-delfino/ansible-collections
issues: https://github.com/x-delfino/ansible-collections/issues

build_ignore: []
