---
- hosts: all
  roles:
    - alacritty
    - curl
    - git
    - golang
    - neovim
    - nnn
    - ohmyzsh
    - python3.9_venv
    - rust
    - rust_analyzer
    - powershell
    - ps_script_analyzer
    - tmux
    - tmuxp
    - tpm
    - unzip
    - vim_plug
    - wget
    - zip
    - zsh
