---
namespace: x_delfino
name: vm_utils
version: 0.0.1
description: collection of virtual machine utilities
tags: []
authors: delfino

readme: README.md
license:
  - GPL-2.0-or-later
license_file: ''

dependencies: {}

repository: https://github.com/x-delfino/ansible-vmutils
documentation: https://github.com/x-delfino
homepage: https://github.com/x-delfino
issues: https://github.com/x-delfino/ansible-vm-utils/issues

build_ignore: []
