---
namespace: x_delfino
name: vm_utils
version: 0.0.2
description: collection of virtual machine utilities
tags: []
authors: delfino

readme: README.md
license:
  - GPL-2.0-or-later
license_file: ''

dependencies: {}

repository: https://github.com/x-delfino/ansible-collections/tree/main/vm-utils
documentation: https://github.com/x-delfino/ansible-collections/tree/main/vm-utils
homepage: https://github.com/x-delfino/ansible-collections
issues: https://github.com/x-delfino/ansible-vm-utils/issues

build_ignore: []
