---
- name: check installed
  ansible.builtin.command: ~/.cargo/bin/alacritty -V
  register: version
  changed_when: false
  failed_when: false

- name: install
  include_tasks: rust_build.yml
  when: version.rc != 0
