---
- name: check installed
  ansible.builtin.command:
    cmd: "pwsh -nop -noni -c '(get-module az -ListAvailable)'"
  register: module
  changed_when: false
  failed_when: false

- name: install
  when: module.stdout == ""
  ansible.builtin.command: "pwsh -nop -noni -c 'install-module Az -Force'"
